version: "2.1"
services:
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    restart: always 
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - ${SAMBA_SHARE}:/mnt
    environment:
      - USERID=${PGUID}
      - GROUPID=${PGID}
      - TZ=${TIME_ZONE}
      - WORKGROUP=WORKGROUP  
      - USER=test;test  
      - RECYCLE=false  
      - SHARE=${SAMBA_SHARE_NAME};/mnt;yes;no;yes;;
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    network_mode: host
    restart: always 
    volumes:
      - ${MINIDLNA_SHARE}:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=${MINIDLNA_NAME}
      - PUID=${PGUID}
      - PGID=${PGID}
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:arm32v7-version-14.3.3.99202101191832-7248-da0b276d5ubuntu18.04.1
    container_name: qbittorrent
    environment:
      - PUID=${PGUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${QB_CONFIG}:/config
      - ${QB_DOWNLOADS}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 80:8080
    restart: always
